# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0079f9d325c4bb64a01ab2608a5c5bb9c4dd8d0cbf755edbf446f03775fd4b3a07da713bb79447d45e6b389c326e747855e670c612d49c8bb3cb421f140530ec

test:
  secret_key_base: fb739d2b95de54f155d29c2823a5ac26445ad3677b54ac4f53161cad4c65a60f23e7eadba9a05e2b73ea86805ec00a70c2ed4249c4e52ab4a93a462f49f09056

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
